### ISSUE TITLE
TensorFlow runtime error

### ISSUE THREAD

**Issue by Diego92Ita** [boy1dr/SpleeterGui#10]
This is the first time using this fantastic application and I always get this error message (I'm italian, I tryed to translate the message for you, but I'm also putting the original if you can't understand what it's saying):

ENG: ImportError: DLL load failed: Initialization routine of the dynamic link library (DLL) failed.

ITA: ImportError: DLL load failed: Routine di inizializzazione della libreria di collegamento dinamico (DLL) non riuscita.

It also prints me this message: Failed to load the native TensorFlow runtime.

What can I do?

**Comment by boy1dr** [comment]
i'm not sure but their may be another python install on your computer. you can try to uninstall SpleeterGUI and install it again.
There may also be a problem with language, special characters in your file paths may not be handled correctly.
if re-install doesn't help you might have to use the older version that doesn't use an MSI installer so you can place it in a simpler file location on your hard drive.

**Comment by Smithug** [comment]
I ran it on 2 different songs in spleeter2 gui , it renamed them as bass, accompaniment and other. all the files were just converted to wave and all three generated the same sound as the original samples, did I miss anything?
