### ISSUE TITLE
Everytime I try any file I get this: Error: Invalid value for 'FILES...': File 'How' does not exist.

### ISSUE THREAD

**Issue by simixrd** [boy1dr/SpleeterGui#105]
As the title says everytime I try to make an acapella I get this message: Error: Invalid value for 'FILES...': File 'How' does not exist.
The 'How' could be anything depending on the file.

**Comment by simixrd** [comment]
(solved it)

**Comment by boy1dr** [comment]
Hi mate, what was the problem in the end?
I'll see if i can update the help page if i've missed something or there's a new issue going on.

**Comment by rivzzzzz** [comment]
Hi I wonder how you solved this issue, much appreciated :)
