### ISSUE TITLE
Allan Mathew

### ISSUE THREAD

**Issue by 2570444** [boy1dr/SpleeterGui#107]
Sir, I had a new RYZEN5 NVIDIA laptop, I have installed Spleeter GYUI for personal use, 
Checked AVX = YES, 
I  processed a song and got the following error message with  empty output folder: no accompaniments or vocals in the folder 
 Starting processing of all songs
Processing D:\Maramon Songs\09-Naadha Nin Munpil...mp3
ERROR:spleeter:FFMPEG error: b"ffmpeg version git-2019-11-01-53c21c2 Copyright (c) 2000-2019 the FFmpeg developers\r\n  built with gcc 9.2.1 (GCC) 20191010\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf\r\n  libavutil      56. 35.101 / 56. 35.101\r\n  libavcodec     58. 60.100 / 58. 60.100\r\n  libavformat    58. 33.100 / 58. 33.100\r\n  libavdevice    58.  9.100 / 58.  9.100\r\n  libavfilter     7. 66.100 /  7. 66.100\r\n  libswscale      5.  6.100 /  5.  6.100\r\n  libswresample   3.  6.100 /  3.  6.100\r\n  libpostproc    55.  6.100 / 55.  6.100\r\nGuessed Channel Layout for Input Stream #0.0 : stereo\r\nInput #0, f32le, from 'pipe:':\r\n  Duration: N/A, bitrate: 2822 kb/s\r\n    Stream #0:0: Audio: pcm_f32le, 44100 Hz, stereo, flt, 2822 kb/s\r\nD:\\Spleeter Tracks\\09-Naadha Nin Munpil../accompaniment.wav: No such file or directory\r\n"
Finished processing all songs

Run complete

I checked all the issues and comments in this site, not showing anything,  can u  help me for this issue..

**Comment by boy1dr** [comment]
in the error message it says your file is
D:\Spleeter Tracks\09-Naadha Nin Munpil../accompaniment.wav
That's a strange path. can you try again with the file in a more simple path like c:\song.mp3 ?

**Comment by boy1dr** [comment]
and output folder like c:\output

**Comment by 2570444** [comment]
Yes, it is working good now,  thanks for your help, much appreciated,, 
Allan
