### ISSUE TITLE
New version not working for me

### ISSUE THREAD

**Issue by NickWinston123** [boy1dr/SpleeterGui#109]
I was using an old version and it was working fine but the outputted clips had a clipping sound in it so I wanted to update to see if that was fixed. I updated through the GUI (update core) and got this error, after uninstalling and reinstalling I still get the error

```
Starting processing of all songs
Processing C:\Users\bestg\Desktop\YM sample 4.wav
Usage: __main__.py separate [OPTIONS] FILES...
Try '__main__.py separate --help' for help.
Error: Missing argument 'FILES...'.
Finished processing all songs

Run complete
```

**Comment by boy1dr** [comment]
There was a change made by deezer to the command line so you will need to grab the latest SpleeterGUI.
Or you can just grab the exe file from here https://github.com/boy1dr/SpleeterGui/tree/master/SpleeterGui/bin/Release
and put it in C:\Program Files (x86)\Maken it so\SpleeterGUI

**Comment by NickWinston123** [comment]
Thanks, this fixed it! I thought I updated but I guess not. And the clipping sound in the outputted clips is gone, awesome

**Comment by boy1dr** [comment]
No worries mate.
I'm working on a better way to keep everything updated ;)

**Comment by maxmerben** [comment]
I have the same problem and this exe file does not help :(
