### ISSUE TITLE
output names

### ISSUE THREAD

**Issue by MixerJr** [boy1dr/SpleeterGui#111]
is there a way to maintain the input file name in the output files?
ex;  input-moonlight.wav
      output-moonlight vocals.wav

**Comment by boy1dr** [comment]
Hi MixerJr
There's no option in SpleeterGUI for it, but you can "hack" it in for now.
once you set your output folder, just paste the following in after the folder text....no spaces or anything, just paste it in

" -f "{foldername}/{filename}_{instrument}.{codec}

**Comment by MixerJr** [comment]
lol wow that was cool
so now is there a way we can hack so only the instrumental output?
thanx man ur the best!!

**Comment by boy1dr** [comment]
Cheers :)
Not at this stage. Spleeter can separate music but you get all the output files, there's no option to only output one of them.
But you could use my Recombine feature to pick the bits you do want.
