### ISSUE TITLE
[Bug] Spleeter renders the song, but it doesn't create the file

### ISSUE THREAD

**Issue by AldoTN** [boy1dr/SpleeterGui#112]
```
Starting processing of all songs
Processing C:\Users\aldot\Desktop\file.mp3
Finished processing all songs

Run complete
```
After this no new files are created, not in the desktop nor in a specific folder

**Comment by boy1dr** [comment]
What version of SpleeterGUI are you using?

**Comment by AldoTN** [comment]
2.9 GUI, spleeter 2.2.2

**Comment by AldoTN** [comment]
update: just realized that it only happens when separating 5 tracks
![image](https://user-images.githubusercontent.com/84485047/118906614-b218f880-b8e3-11eb-9356-a61d650f3a6c.png)

**Comment by boy1dr** [comment]
That's weird that it fails only on 5 part separation.
Delete this folder and try it again (spleeter will re-download that folder on next run)...
C:\Users\aldot\AppData\Roaming\SpleeterGUI\pretrained_models\5stems

Your system font size looks to be increased, the current version of my app doesn't account for this. The next one does but it's a little ways off.
It's just the high quality mode option which is enabled by default.

**Comment by AldoTN** [comment]
had to reset the font size and to delete the folder, it now works again, tysm for helping me and for developing this UI
![image](https://user-images.githubusercontent.com/84485047/118908281-beeb1b80-b8e6-11eb-9e26-20870d9fd1b6.png)
