### ISSUE TITLE
Spleeter Error 

### ISSUE THREAD

**Issue by GTY996** [boy1dr/SpleeterGui#115]
Hi everyone ! i just downloaded spleeter gui yesterday but i got this errror json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 

can anyone help me ? thank you in advance !

**Comment by boy1dr** [comment]
Hi
This isn't an error i have seen before.
Was there any other details with that error message?

**Comment by GTY996** [comment]
Here is the full text box in SpleeterGUI software !

Starting processing of all songs
Processing D:\The Thrill Porter Robinson Remix_ - Nero.wav
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in <module>
    entrypoint()
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 250, in entrypoint
    spleeter()
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 131, in separate
    synchronous=False,
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 380, in separate_to_file
    sample_rate=self._sample_rate,
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\ffmpeg.py", line 101, in load
    probe = ffmpeg.probe(path)
  File "C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\ffmpeg\_probe.py", line 24, in probe
    return json.loads(out.decode('utf-8'))
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 348, in loads
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\decoder.py", line 337, in decode
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Finished processing all songs

Run complete

Well it's said Run Complete but when i open the output folder non of my audio file there ?, when i drag and drop it's seem run normanly Lol , the whole text box seems fine except last line ? json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by boy1dr** [comment]
it looks to be having trouble reading some JSON files.
Try taking out all the spaces from the source audio file. it shouldn't matter but let's see anyway.
Otherwise i would try re-installing SpleeterGUI

**Comment by GTY996** [comment]
Honesty i have no idea where i did wrong lol, i tired reinstall and everything but it's still show same error, looks like no one have same issue like me Lol .........

**Comment by boy1dr** [comment]
Try clicking Help, then Spleeter core upgrade.
paste the result in here.
I can give you some more commands to try if that doesn't work ;)

**Comment by GTY996** [comment]
Here you go !, and Yes i still got same error after this :))

Running update command
This might take a while, wait for the beep

Requirement already up-to-date: spleeter in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (2.2.2)
Requirement already satisfied, skipping upgrade: importlib-metadata<4.0.0,>=3.0.0; python_version < "3.8" in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from spleeter) (3.10.1)
Requirement already satisfied, skipping upgrade: numpy<1.19.0,>=1.16.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from spleeter) (1.17.3)
Requirement already satisfied, skipping upgrade: tensorflow==2.3.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from spleeter) (2.3.0)
Requirement already satisfied, skipping upgrade: norbert==0.2.1 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from spleeter) (0.2.1)
Requirement already satisfied, skipping upgrade: typer<0.4.0,>=0.3.2 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from spleeter) (0.3.2)
Requirement already satisfied, skipping upgrade: librosa==0.8.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from spleeter) (0.8.0)
Requirement already satisfied, skipping upgrade: httpx[http2]<0.17.0,>=0.16.1 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from spleeter) (0.16.1)
Requirement already satisfied, skipping upgrade: pandas==1.1.2 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from spleeter) (1.1.2)
Requirement already satisfied, skipping upgrade: ffmpeg-python==0.2.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from spleeter) (0.2.0)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.6.4; python_version < "3.8" in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from importlib-metadata<4.0.0,>=3.0.0; python_version < "3.8"->spleeter) (3.10.0.0)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from importlib-metadata<4.0.0,>=3.0.0; python_version < "3.8"->spleeter) (3.4.1)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (1.1.0)
Requirement already satisfied, skipping upgrade: absl-py>=0.7.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (0.8.1)
Requirement already satisfied, skipping upgrade: google-pasta>=0.1.8 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (0.1.8)
Requirement already satisfied, skipping upgrade: protobuf>=3.9.2 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (3.10.0)
Requirement already satisfied, skipping upgrade: six>=1.12.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (1.13.0)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (0.33.6)
Requirement already satisfied, skipping upgrade: keras-preprocessing<1.2,>=1.1.1 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (1.1.2)
Requirement already satisfied, skipping upgrade: tensorflow-estimator<2.4.0,>=2.3.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (2.3.0)
Requirement already satisfied, skipping upgrade: astunparse==1.6.3 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (1.6.3)
Requirement already satisfied, skipping upgrade: wrapt>=1.11.1 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (1.11.2)
Requirement already satisfied, skipping upgrade: h5py<2.11.0,>=2.10.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (2.10.0)
Requirement already satisfied, skipping upgrade: tensorboard<3,>=2.3.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (2.3.0)
Requirement already satisfied, skipping upgrade: grpcio>=1.8.6 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (1.25.0)
Requirement already satisfied, skipping upgrade: scipy==1.4.1 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (1.4.1)
Requirement already satisfied, skipping upgrade: opt-einsum>=2.3.2 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (3.2.1)
Requirement already satisfied, skipping upgrade: gast==0.3.3 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorflow==2.3.0->spleeter) (0.3.3)
Requirement already satisfied, skipping upgrade: click<7.2.0,>=7.1.1 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from typer<0.4.0,>=0.3.2->spleeter) (7.1.2)
Requirement already satisfied, skipping upgrade: soundfile>=0.9.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from librosa==0.8.0->spleeter) (0.10.3.post1)
Requirement already satisfied, skipping upgrade: resampy>=0.2.2 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from librosa==0.8.0->spleeter) (0.2.2)
Requirement already satisfied, skipping upgrade: audioread>=2.0.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from librosa==0.8.0->spleeter) (2.1.8)
Requirement already satisfied, skipping upgrade: pooch>=1.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from librosa==0.8.0->spleeter) (1.2.0)
Requirement already satisfied, skipping upgrade: numba>=0.43.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from librosa==0.8.0->spleeter) (0.49.0)
Requirement already satisfied, skipping upgrade: joblib>=0.14 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from librosa==0.8.0->spleeter) (0.14.1)
Requirement already satisfied, skipping upgrade: decorator>=3.0.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from librosa==0.8.0->spleeter) (4.4.2)
Requirement already satisfied, skipping upgrade: scikit-learn!=0.19.0,>=0.14.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from librosa==0.8.0->spleeter) (0.22.2.post1)
Requirement already satisfied, skipping upgrade: rfc3986[idna2008]<2,>=1.3 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from httpx[http2]<0.17.0,>=0.16.1->spleeter) (1.4.0)
Requirement already satisfied, skipping upgrade: certifi in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from httpx[http2]<0.17.0,>=0.16.1->spleeter) (2019.9.11)
Requirement already satisfied, skipping upgrade: sniffio in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from httpx[http2]<0.17.0,>=0.16.1->spleeter) (1.2.0)
Requirement already satisfied, skipping upgrade: httpcore==0.12.* in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from httpx[http2]<0.17.0,>=0.16.1->spleeter) (0.12.3)
Requirement already satisfied, skipping upgrade: h2==3.*; extra == "http2" in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from httpx[http2]<0.17.0,>=0.16.1->spleeter) (3.2.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from pandas==1.1.2->spleeter) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from pandas==1.1.2->spleeter) (2019.3)
Requirement already satisfied, skipping upgrade: future in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from ffmpeg-python==0.2.0->spleeter) (0.16.0)
Requirement already satisfied, skipping upgrade: setuptools in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from protobuf>=3.9.2->tensorflow==2.3.0->spleeter) (41.6.0)
Requirement already satisfied, skipping upgrade: tensorboard-plugin-wit>=1.6.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (1.7.0)
Requirement already satisfied, skipping upgrade: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (0.4.2)
Requirement already satisfied, skipping upgrade: google-auth<2,>=1.6.3 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (1.23.0)
Requirement already satisfied, skipping upgrade: requests<3,>=2.21.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (2.22.0)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (3.1.1)
Requirement already satisfied, skipping upgrade: werkzeug>=0.11.15 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (0.16.0)
Requirement already satisfied, skipping upgrade: cffi>=1.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from soundfile>=0.9.0->librosa==0.8.0->spleeter) (1.14.0)
Requirement already satisfied, skipping upgrade: appdirs in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from pooch>=1.0->librosa==0.8.0->spleeter) (1.4.4)
Requirement already satisfied, skipping upgrade: packaging in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from pooch>=1.0->librosa==0.8.0->spleeter) (20.4)
Requirement already satisfied, skipping upgrade: llvmlite<=0.33.0.dev0,>=0.31.0.dev0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from numba>=0.43.0->librosa==0.8.0->spleeter) (0.32.0)
Requirement already satisfied, skipping upgrade: idna; extra == "idna2008" in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from rfc3986[idna2008]<2,>=1.3->httpx[http2]<0.17.0,>=0.16.1->spleeter) (2.8)
Requirement already satisfied, skipping upgrade: h11==0.* in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from httpcore==0.12.*->httpx[http2]<0.17.0,>=0.16.1->spleeter) (0.12.0)
Requirement already satisfied, skipping upgrade: hyperframe<6,>=5.2.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from h2==3.*; extra == "http2"->httpx[http2]<0.17.0,>=0.16.1->spleeter) (5.2.0)
Requirement already satisfied, skipping upgrade: hpack<4,>=3.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from h2==3.*; extra == "http2"->httpx[http2]<0.17.0,>=0.16.1->spleeter) (3.0.0)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=0.7.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (1.3.0)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (0.2.8)
Requirement already satisfied, skipping upgrade: rsa<5,>=3.1.4; python_version >= "3.5" in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (4.6)
Requirement already satisfied, skipping upgrade: cachetools<5.0,>=2.0.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (4.1.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (1.25.6)
Requirement already satisfied, skipping upgrade: pycparser in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from cffi>=1.0->soundfile>=0.9.0->librosa==0.8.0->spleeter) (2.20)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from packaging->pooch>=1.0->librosa==0.8.0->spleeter) (2.4.7)
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (3.1.0)
Requirement already satisfied, skipping upgrade: pyasn1<0.5.0,>=0.4.6 in c:\users\tquoc\appdata\roaming\spleetergui\python\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow==2.3.0->spleeter) (0.4.8)

Run complete

**Comment by boy1dr** [comment]
ARGH python can be infuriating at times lol.
So what i will suggest will require a little command line knowledge but stick with me.
Press start and type "cmd" then hit enter.
You will want to copy, paste and run each of these commands separately.
The 2nd & 3rd commands will take a while to run.
Feel free to paste back any output you think might have gone wrong.

cd C:\Users\tquoc\AppData\Roaming\SpleeterGUI\python
python -m pip uninstall spleeter tensorflow
python -m pip install spleeter

This will take you to the python folder, uninstall spleeter, then install it again.
After that, give it a go again, hopefully whatever went wrong during install is now overwritten by pip and you can go do your thing.

**Comment by GTY996** [comment]
Hey i just did exactly like you said and it's worked :), well i think it's has something to do with the python, i tried to uninstall my old python and then reinstall spleeter then it's work fine now,i know it's not how it's suppose to work but it's work anyway lmao, thank you very much you dude ! ........
