### ISSUE TITLE
ffmpeg error during processing. No output files made.

### ISSUE THREAD

**Issue by shades-aus** [boy1dr/SpleeterGui#119]
I don't seem to be able to qualify any paths for required applications like ffmpeg, so, I am unsure how to check the configuration.
The output of the GUI seems to have \\ double back slashes. I am unsure if this is a problem.
Windows 10 21H1 - 19043.1110 - x64, Core i7 4770S CPU with AVX, 32 GB RAM 
It is a part of a domain, I don't know if that's a problem or not.

Here is the output message from the GUI:
Starting processing of all songs
Processing D:\Band\Sessions\Rest_in_peace_ng .wav
ERROR:spleeter:FFMPEG error: b"ffmpeg version git-2019-11-01-53c21c2 Copyright (c) 2000-2019 the FFmpeg developers\r\n  built with gcc 9.2.1 (GCC) 20191010\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf\r\n  libavutil      56. 35.101 / 56. 35.101\r\n  libavcodec     58. 60.100 / 58. 60.100\r\n  libavformat    58. 33.100 / 58. 33.100\r\n  libavdevice    58.  9.100 / 58.  9.100\r\n  libavfilter     7. 66.100 /  7. 66.100\r\n  libswscale      5.  6.100 /  5.  6.100\r\n  libswresample   3.  6.100 /  3.  6.100\r\n  libpostproc    55.  6.100 / 55.  6.100\r\nGuessed Channel Layout for Input Stream #0.0 : stereo\r\nInput #0, f32le, from 'pipe:':\r\n  Duration: N/A, bitrate: 2822 kb/s\r\n    Stream #0:0: Audio: pcm_f32le, 44100 Hz, stereo, flt, 2822 kb/s\r\nD:\\Band\\DL\\Rest_in_peace_ng /other.wav: No such file or directory\r\n"
Finished processing all songs

Run complete

**Comment by shades-aus** [comment]
Ok.
I resolved this issue by shortening the filename and taking out the space before the period "full-stop" extension marker.

**Comment by boy1dr** [comment]
@shades-aus yes spleeter has trouble with spaces at the end of file paths. glad you got it working :)
