### ISSUE TITLE
No separate stems generated

### ISSUE THREAD

**Issue by Smithug** [boy1dr/SpleeterGui#12]
I ran it on 2 different songs in spleeter2 gui , it successfully renamed them as bass, accompaniment and other. all the files were just converted to wave and all three generated the same sound as the original samples, did I miss anything?

_Originally posted by @Smithug in https://github.com/boy1dr/SpleeterGui/issues/10#issuecomment-613449676_

**Comment by boy1dr** [comment]
the first time you run spleeter in 2, 4 & 5 stem mode, python.exe will download the pretrained model data.
once each stem model is downloaded no further downloads are required.
check your anti-virus or firewall isn't blocking the download.
The downloaded files (2stems,4stems,5stems) will be placed in the folder C:\Users\chris\AppData\Roaming\SpleeterGUI\pretrained_models (your username of course).
