### ISSUE TITLE
Dosent output

### ISSUE THREAD

**Issue by Knotzer** [boy1dr/SpleeterGui#120]
I use it, and it says it's complete and there was no issues, but no matter what I do, it isn't in the folder I set it too.

**Comment by boy1dr** [comment]
can you copy in all the text that it shows when it says complete thanks

**Comment by Knotzer** [comment]
Starting processing of all songs
Processing D:/vocal only\5am.mp3
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
there is something wrong with that file path "Processing D:/vocal only\5am.mp3"

**Comment by Knotzer** [comment]
I have changed the file path at least 5 times
