### ISSUE TITLE
SpleeterGUI 2.9.1 doesn't work after installing with SpleeterGUI_V2.9.1.msi

### ISSUE THREAD

**Issue by SJegorovs** [boy1dr/SpleeterGui#123]
Hey there,

I've installed SpleeterGUI Version 2.9.1 with the installer version (msi) on my AMD (2 Core E350E) PC with Windows 10 (20H02).

The GUI starts, but it's running in an TensorFlow error. When I go to the GUIs Help Tab to run spleeter core-upgrade I get an error message, that the pyton.exe is missing. Is there an incomplete installation of the portable version of pyton?

Who can help me out on that issue?

Best regards from Travemünde/Baltic Mare / Germany

Svens

**Comment by boy1dr** [comment]
Please see common problem # 1  https://makenweb.com/spleeter_help

If you see "ImportError: DLL load failed" your CPU unfortunately won't run spleeter.
