### ISSUE TITLE
Bandwidth/Quality check box issue

### ISSUE THREAD

**Issue by Instrumentallyinsane** [boy1dr/SpleeterGui#13]
Thank you for this fantastic tool! The only issue I've had is the "[ ] Full Bandwidth (High Quality)" check box. By default, it shows it is checked. However, the output files have no frequencies above 11kHz. In order to get it to work properly, I uncheck and recheck the box every time I open the GUI. That produces full bandwidth.
![x](https://user-images.githubusercontent.com/64747009/80921625-2b22cd80-8d2c-11ea-8f8d-2194a6eb2f80.jpg)

**Comment by Zcooger** [comment]
Yes, I confirm this issue too.

**Comment by boy1dr** [comment]
Right you are, thanks for letting me know. I have fixed the bug and deployed changes to github.
SpleeterGUI is now at version 2.4

A quick way to update is to copy from this repository the "SpleeterGui\bin\Release\SpleeterGui.exe" file over to "C:\Program Files (x86)\Maken it so\SpleeterGUI"

I will publish a new MSI installer soon.

**Comment by boy1dr** [comment]
The new installer is now available on my website https://makenweb.com/spleeter2.php
You will have to uninstall the previous version before installing this one.

**Comment by Instrumentallyinsane** [comment]
> The new installer is now available on my website https://makenweb.com/spleeter2.php
> You will have to uninstall the previous version before installing this one.

Thank you!
