### ISSUE TITLE
Any access to the 2.6 version of the GUI?

### ISSUE THREAD

**Issue by Instrumentallyinsane** [boy1dr/SpleeterGui#130]
I tried the 2.9 upgrade, but it doesn't work. Does anyone have a link to 2.6? That one worked fine for me.

**Comment by boy1dr** [comment]
Here's a link to V2.6 https://makenweb.com/downloads/SpleeterGUI_V2.6.msi
There is a bug with the latest Spleeter update script so if you download V2.9.1 (latest) just don't click the spleeter core upgrade until Deezer have addressed the issue.
