### ISSUE TITLE
Is there a way to change bitrate?

### ISSUE THREAD

**Issue by AftabAhmad** [boy1dr/SpleeterGui#132]
Output files have a static bitrate is there a way to increase/decrease bitrate based on requirement?

**Comment by boy1dr** [comment]
There is a json configuration file you can adjust parameters as you see fit.
C:\Users\YOUR-ACCOUNT\AppData\Roaming\SpleeterGUI\config.json
There isn't a lot of documentation on how this file works but google deezer spleeter json config file and you will find some results that may help
