### ISSUE TITLE
Feature Request: video file support

### ISSUE THREAD

**Issue by bloworlf** [boy1dr/SpleeterGui#133]
That bothers me everytime I have to convert a video to audio then drag the converted file to SpleeterGui.

It would be very nice if the program could support video file: it would convert it itself then process to split it.

**Comment by boy1dr** [comment]
Spleeter is a music source separation utility and as such is not meant for video sorry. Adding additional ffmpeg commands to the GUI to split and recombine video is problematic to say the least. If it was simple to add i would.

**Comment by bloworlf** [comment]
Sorry, I didn't mean to reprocess the video file. Just drag and drop a video file, Spleeter would extract the audio and split it.

**Comment by boy1dr** [comment]
All good, i agree this would be a useful feature. But every spare second i have to devote to this project is consumed by figuring out how to keep spleeter running on windows without a convoluted python installation. Maybe in a couple of months i can direct a bit more attention to some of these feature requests.
