### ISSUE TITLE
ver2.3.msi

### ISSUE THREAD

**Issue by pippalatree** [boy1dr/SpleeterGui#135]
It's a new PC.
I used the oldest version 2.7 currently available for download.
It does not work even if I replace it with Spleeter 1.4.3.
There is no pop noise, but there is a blank time in the intro.
SpleeterGUI v2.3 was great software. There was nothing wrong with it.
Could you please make this version available for download?

**Comment by boy1dr** [comment]
i'll post a link to SpleeterGUI 2.3 in a few hours when i get home.
There's not much change in the GUI code between 2.3 and 2.9, i had to upgrade the project to 64bits to avoid a common malware false positive.
The latest Spleeter version is currently not working so when you download SpleeterGUI do not run the core upgrade or it will break. run it as is and keep checking my website for news of the fix when it happens.

**Comment by pippalatree** [comment]
Thank you for your support. I look forward to the link.
2.6-2.9.1, Blank occurs in all versions. Or there is pop noise instead.
My PC has this configuration.
Windows10 Pro, AMD ryzen 3600 and GTX1650.

**Comment by boy1dr** [comment]
i only have versions 2.6 through 2.9.1 hosted.
But the GUI doesn't really dictate the spleeter version being used, you can always change it if you are willing to use a few dos commands.

First, open a command window (press windows key, type "cmd" and enter).
Then you will need to change directory to YOUR spleeterGUI folder. change "chris" to your windows username.
```
cd C:\Users\chris\AppData\Roaming\SpleeterGUI\python
```
Then you need to uninstall the spleeter package by running this command.
```
python -m pip uninstall spleeter
```
Then you can install whichever version of spleeter you want, use this command but change the version number to what you want.
```
python -m pip install spleeter==2.2.2
```

These are the available spleeter versions

1.4.1, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 2.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0

**Comment by pippalatree** [comment]
Hi @boy1dr ,

I tried your support.
However, the results obtained were the same.
Spleeter version is set to 1.4.1.

And this was also confirmed on my clean install of Windows 10.
Even on a sub PC.

Has ver2.3.msi been lost forever?

**Comment by pippalatree** [comment]
https://github.com/boy1dr/SpleeterGui/issues/26

Seems to be a problem in the thread.

I saw this thread when I was using v2.3.
But now the core upgrade is deadly.
Is there a command to specify Core2.0?

**Comment by boy1dr** [comment]
@pippalatree Deezer's advice was to add "-B tensorflow" to the command line to fix the audio click/pops in the earlier versions of Spleeter. They have since fixed that issue so i removed that -B command.
If you're not able to adjust the current project with that command line addition and recompile let me know and i'll shoot you a custom build.

**Comment by pippalatree** [comment]
The problem is gone.
thank you. Convenient software, I will continue to use it habitually.
