### ISSUE TITLE
the max audio is 7200s,i want more.

### ISSUE THREAD

**Issue by EnderOcelot** [boy1dr/SpleeterGui#138]
How to edit audio length over 7200s

**Comment by boy1dr** [comment]
not sure why i put a 7200 limit on the max length, i'll update the project soon.
in the meantime i compiled an update for you https://1drv.ms/u/s!AhbM98WiPUJYmU3Y7cTfz4wQFyXu?e=W6oZhA
just pop it in C:\Program Files (x86)\Maken it so\SpleeterGUI
overwrite existing.
