### ISSUE TITLE
i can only split into 2 stems. When i tried 4 or 5 stems i get this...

### ISSUE THREAD

**Issue by Hexie11020** [boy1dr/SpleeterGui#139]
ffmpeg version git-2019-11-01-53c21c2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191010
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 35.101 / 56. 35.101
  libavcodec     58. 60.100 / 58. 60.100
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 66.100 /  7. 66.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
C:\Users\Admin\Desktop\out\เธเนเธฒเธเธฐเธ•เนเธญเธเธเธฅเธฑเธงเธชเธดเนเธเนเธ” - Why Should I Be Afraid [Karaoke]\bass.wav: No such file or directory

**Comment by boy1dr** [comment]
maybe the filename can be simpler, looks like some special characters there.
But normally when 2 stem works and 4/5 don't, you need to remove the AI models and run those spleet's again.
Go to C:\Users\Admin\AppData\Roaming\SpleeterGUI\pretrained_models
Delete the folders "4stems" and "5stems".
Next time you use 4 & 5 stem spleet it will download those models again.
