### ISSUE TITLE
SpleeterGUI 2.9 / python.exe is missing / How to set Python path

### ISSUE THREAD

**Issue by SJegorovs** [boy1dr/SpleeterGui#140]
Hello to all,

I've setup a new music PC with a Intel I7 quadcore CPU and 16 GB RAM.

Now I've installed SpleeterGUI_V2.9.1.msi. After opening the Gui it says "Python.exe not found". When I click to "Advanced->Set SpleetGuiPath" and I change it to the installation path, I get again the error message. In the Explorer i cannot find at the installation directory (and subdirectories) a Python-installation. What can I do, to get SpleeterGUI running?

I prechate all hints.

Best regards from Germany
Svens

**Comment by boy1dr** [comment]
hi
My path is   C:\Users\chris\AppData\Roaming\SpleeterGUI
The folder "AppData" is a hidden folder so you will need to change the windows explorer folder options to "show hidden files, folders, or drives"

**Comment by SJegorovs** [comment]
Dear Chris, I installed SpleeterGUI 2.9 again and find the python.exe on the equal directory on my music PC. But if I try to set the path in SpleeterGUI to the python.exe location, I get still the message "Unable to find python.exe". Can it help to copy the python directory to for exaple to drive d: and use this directory for the SpleeterGUI path info? Or will a manual change the path info in the registry? Best regards Svens Am 13.01.2022 00:49 schrieb Chris Mitchell ***@***.***>:
hi
My path is   C:\Users\chris\AppData\Roaming\SpleeterGUI
The folder "AppData" is a hidden folder so you will need to change the windows explorer folder options to "show hidden files, folders, or drives"

**Comment by boy1dr** [comment]
Choose the spleeterGUI folder

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Cervellie** [comment]
Hi, I'm having the same problem as SJegorovs. When I open the "Set SpleeterGUI path" tab, I can't see python.exe. To be more precise, I cannot click on python.exe because it is not visible.
(My path is C:\Users\username\AppData\Local\Programs\Python\Python310)

<img width="295" alt="repo2" src="https://user-images.githubusercontent.com/97950128/149922909-bb15ae57-55ef-43e9-828f-12e9157681b3.png">
<img width="208" alt="repo" src="https://user-images.githubusercontent.com/97950128/149922916-d477c252-063c-4472-8dc1-4b630b0325e9.png">

**Comment by SJegorovs** [comment]
Hello again,I find following workarround:I copy the folder Make_it_so to drive d:Then i copy from the SpleeterGUI folder, which includes the python files, the python folder to the SpleeterGUI folder into the SpleeterGUI folder on drive d:Finally I changed the path inofs in the desktop link to the new location on drive d:Now SpleeterGUI starts without any error message. And splitting is working, as asumed. Now my final question:On start of the app it shows as version info "2.1.2" but on the top of the app is shown "SpleeterGUI 2.9". Do I have the actual version or where I can find the newest one? Best regards Svens Am 18.01.2022 11:51 schrieb Cervellie ***@***.***>:
Hi, I'm having the same problem as SJegorovs. When I open the "Set SpleeterGUI path" tab, I can't see python.exe. To be more precise, I cannot click on python.exe because it is not visible.
(My path is C:\Users\username\AppData\Local\Programs\Python\Python310)



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
Am 18.01.2022 11:51 schrieb Cervellie ***@***.***>:
Hi, I'm having the same problem as SJegorovs. When I open the "Set SpleeterGUI path" tab, I can't see python.exe. To be more precise, I cannot click on python.exe because it is not visible.
(My path is C:\Users\username\AppData\Local\Programs\Python\Python310)



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
Am 18.01.2022 11:51 schrieb Cervellie ***@***.***>:
Hi, I'm having the same problem as SJegorovs. When I open the "Set SpleeterGUI path" tab, I can't see python.exe. To be more precise, I cannot click on python.exe because it is not visible.
(My path is C:\Users\username\AppData\Local\Programs\Python\Python310)

**Comment by boy1dr** [comment]
Choose the spleeterGUI folder.
No need to choose the python.exe file just choose the spleeterGUI folder.
