### ISSUE TITLE
"TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'" after upgrading Spleeter core?

### ISSUE THREAD

**Issue by JudgementTimeSPD** [boy1dr/SpleeterGui#143]
The program wasn't outputting anything, so in a vain attempt to fix it I tried to upgrade the Spleeter core. Once it finished, I tried to run a file through it again, only to give the above message. Below is a capture of what I'm seeing. Thanks in advance for any help!
![problem](https://user-images.githubusercontent.com/24262452/152268166-03d249b6-bc77-49f1-b81f-adc9b2e02b5b.png)

**Comment by boy1dr** [comment]
This is a known spleeter bug which we are told will be fixed but no timeline has been given.
easiest fix is to uninstall SpleeterGUI and install it again. Don't run the core update until it is confirmed fixed.

There is a notice on my website advising about this bug, i will update the message when the fix comes though
https://makenweb.com/SpleeterGUI
