### ISSUE TITLE
Files are not generated when the duration is large

### ISSUE THREAD

**Issue by jerryleelove** [boy1dr/SpleeterGui#144]
When songs are too long, such as 3000 seconds, no files are generated. Sometimes you don't get an error, sometimes you get an error.

**Comment by boy1dr** [comment]
song length can be specified in the GUI as "Maximum song length" in seconds. it is a memory constraint, not all users have 32GB of ram so to prevent crashing for most people this is limited, you can specify a larger amount if your system is capable of it.
