### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by GravuTrad** [boy1dr/SpleeterGui#15]
Hello.
Could you make a multilingual version? (to able to depose on the project foreign languages)
Thanks.

**Comment by boy1dr** [comment]
Sorry i wouldn't know how to do that, i only know English.
But leave this issue open and with some luck a kind person that knows how to might contribute to this project.

**Comment by GravuTrad** [comment]
My question was only to know if you could manage in the creation of your software to externalize in language file the strings, to permit easier translations. (A patch is possible, but it's easier when all the strings are externalize directly by the software.)

**Comment by boy1dr** [comment]
Which language would you like to see in there?
The next version (2.6) will come with English, Arabic, Chinese, French, Hindi, Russian and Spanish.
Additional languages can be added by altering one of the included XML language files.

**Comment by boy1dr** [comment]
New version 2.6 released today includes multiple languages https://makenweb.com/spleeter2.php

**Comment by GravuTrad** [comment]
Thanks. It was for french.
