### ISSUE TITLE
ERROR:spleeter:ffmpeg binary not found

### ISSUE THREAD

**Issue by KanamiG** [boy1dr/SpleeterGui#152]
I believed that I installed ffmpeg correctly and set it to PATH
![image](https://user-images.githubusercontent.com/104453218/165351546-ba5f83f8-6599-441b-af01-7797426f9e98.png)
![image](https://user-images.githubusercontent.com/104453218/165351774-3349fe2f-18cd-4d72-aefb-884bd61f85f1.png)
![image](https://user-images.githubusercontent.com/104453218/165351829-63734543-a691-4914-b51d-d89bd881aeaf.png)
Before this I tried various different method including pip install ffmpeg and ffmpeg-python, I tried installing both then seperately
but nothing worked so I pip uninstall all my package,reinstall spleeterGUI and went for EXE files the ffmpeg website
It didn't work either
Maybe it's a Windows 11 problem

Full log:
Starting processing of all songs
Processing C:\Users\加波\Desktop\song.mp3
ERROR:spleeter:ffmpeg binary not found
Finished processing all songs

Run complete

**Comment by KanamiG** [comment]
Final update:
After I done trying with older version and having a success, I tried the newest version again and it magically worked.
I have no further questions.

**Comment by sTangtanga** [comment]
I'm having the same issue, I'm going to try the lower version now
