### ISSUE TITLE
Numba 0.48.0 failes, need 0.47.0 but pip is not included in Python distro

### ISSUE THREAD

**Issue by dts350z** [boy1dr/SpleeterGui#16]
Saw the same error with Spleeter on the command line (with another python distro).

From your GUI:
Starting processing of all songs
Processing C:\Users\IEUser\Desktop\01 - Stupid Girls.flac
Traceback (most recent call last):
  File "C:\Users\IEUser\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: The specified module could not be found.

Again, from here: https://github.com/numba/numba/issues/5585

a fix seems to be to downgrade numba with:

pip install --upgrade numba==0.47.0

but the python installed by this MSI doesn't seem to have pip in it.

**Comment by boy1dr** [comment]
pip is included
try this
python -m pip 

sorry i don't know much about python, i had a python friend assemble the embeddable python version used in this project

**Comment by boy1dr** [comment]
New version 2.5 uploaded yesterday has spleeter core upgrade feature in the help menu
should help with issues like these
https://makenweb.com/spleeter2.php
