### ISSUE TITLE
problems about keeping backing vocals while removing vocals

### ISSUE THREAD

**Issue by NoahMarva** [boy1dr/SpleeterGui#162]
Hello! This is my first time here and I'm not sure if my question is appropriate. I've found a common problem with many spleeter based services that remove the backing vocals while removing the vocals, I've only found one service provider online that can do this while removing the vocals and keeping the backing vocals, I'm wondering if SpleeterGUI can do this through training? I have this client on my desktop. Wouldn't it be so much easier if It could do that?

**Comment by boy1dr** [comment]
I have not been able to train spleeter successfully yet. It might be possible to train it with the difference between vocal and backing vocal if they sound distinct enough but i have doubts that this could work using these AI models.
If there is software that can do this i imagine it would be running multiple passes on the output audio to further separate them.

**Comment by NoahMarva** [comment]
> I have not been able to train spleeter successfully yet. It might be possible to train it with the difference between vocal and backing vocal if they sound distinct enough but i have doubts that this could work using these AI models. If there is software that can do this i imagine it would be running multiple passes on the output audio to further separate them.

http://103.153.75.146:94/www1/proxy/lxl26964a96a9a0c46/iodonnadelcorrieredellasera9luglio2022.rar  So far I've seen only one service provider that offers to retain backing vocals while removing the vocals, and presumably it relies on a lot of training to do so?
