### ISSUE TITLE
Spleeter was updated to version 2.3.1 so that cannot process music

### ISSUE THREAD

**Issue by otomad** [boy1dr/SpleeterGui#163]
![image](https://user-images.githubusercontent.com/56647156/180435678-96119f6d-532f-4a5a-912d-dd393b58a585.png)
![image](https://user-images.githubusercontent.com/56647156/180435845-a0470db7-5904-4595-acd2-392b8c7df807.png)
![image](https://user-images.githubusercontent.com/56647156/180435874-6313c310-96e4-4cec-8e1b-654bd568f044.png)

I've just click Help > Spleeter core upgrade.

**Comment by boy1dr** [comment]
The Spleeter core upgrades don't always work, the easiest way to get back to working condition is to uninstall SpleeterGUI and re-install.
