### ISSUE TITLE
Unhandled Exception when trying to click any button

### ISSUE THREAD

**Issue by Humza-H** [boy1dr/SpleeterGui#170]
After accidently closing the app while seperating a song, the program has Unhandled Exceptions when trying to do anything including loading up, I have reinstalled both SpleeterGUI and .NET but no luck

**Comment by Humza-H** [comment]
Fixed by reinstalling to different folder

**Comment by boy1dr** [comment]
crikey, i'll have a look at that. thanks for letting me know ;)
