### ISSUE TITLE
There is nothing in "pretrained_models" folder 

### ISSUE THREAD

**Issue by Wangxuechi** [boy1dr/SpleeterGui#186]
I guess the programme does not download pretrained_models correctly.

**Comment by Wangxuechi** [comment]
And when process finished, the vocals and accompaniment file are the same as original file

**Comment by boy1dr** [comment]
The pretrained model files will be downloaded on the first run.

If the pretrained_models folder is empty after running then something prevented python from downloading the files. check your defender/anti virus. 

If all else fails, try the previous version https://makenweb.com/downloads/old_filezz/SpleeterGUI_V2.9.2.msi

**Comment by boy1dr** [comment]
Just don't run the "spleeter core update" in V2.9.2, it will mess up the spleeter install forcing you to completely remove it and install it again.

**Comment by Wangxuechi** [comment]
Could you provide the pretrained_model file?

**Comment by boy1dr** [comment]
I have provided the download link for V2.9.2 which contains the model files
