### ISSUE TITLE
Possible to reduce folder size of /site-packages?

### ISSUE THREAD

**Issue by PRPoundSix** [boy1dr/SpleeterGui#195]
I see that the total file size of the /site-packages folder is close to 1.5gb. Is there a way to reduce this folder size?

**Comment by boy1dr** [comment]
Not really. Spleeter itself is quite large, and it uses a whole bunch of other packages to do it's job.  
The only way you could save on space is to delete the contents of the pretrained_model folder and only use 1 of the stem options.

Each time you run a new model, it will download the model files which will use space. So pick a model and stick with it.

That is, only use the 2-stem or 4-stem etc for separation.
