### ISSUE TITLE
Possible Features

### ISSUE THREAD

**Issue by bboettcher3** [boy1dr/SpleeterGui#2]
Been working on some improvements for this project, just wanted to run them by you and see if they would make sense to integrate.

1. Debug mode checkbox (in expert tab): only keep command window open after processing if checked, otherwise terminate after processing
     a. Could also hide command window entirely if progress bars are introduced
2. Batching inputs: Drag multiple files in for processing, would need to add progress bars
3. Exporting output files in specific formats
     - eg. Ableton Live clip pack/ hierarchies that allow for easy importing into DAWs

I'd be happy to complete these tasks, just more wondering if you'd be open to outside contributions! :)

**Comment by boy1dr** [comment]
These are great idea's and would like to integrate them in to the project :)
I have been thinking i should move the command window inside the application and provide a toggle to show/hide it (like visual studio debug window).
i like your drag/drop suggestion but batching might be a little harder. i mean, spleeter does support batching but there is no percentage complete output from spleeter to provide a progress bar...maybe only for songs processed.
Setting the output file format is easy as long as it's one of these (wav,mp3,ogg,m4a,wma,flac).
Thoughts?

i'll have quite a bit of time to play with this over the holiday, and maybe even have my python guru friend modify spleeter to give us percentage complete etc.

**Comment by eerilqin** [comment]
非常感谢你 ， 我很喜欢，已经在用了

**Comment by boy1dr** [comment]
很开心听到。我刚刚上传了一个新版本，易于使用
