### ISSUE TITLE
Could not locate zlibwapi.dll. Please make sure it is in your library path!

### ISSUE THREAD

**Issue by fatdennis** [boy1dr/SpleeterGui#206]
"Starting processing of all songs
Processing C:\Users\Dennis\Downloads\WhatsApp Audio 2023-08-10 at 12.19.32 PM.mpeg
Could not locate zlibwapi.dll. Please make sure it is in your library path!
Finished processing all songs"

Though it said finished processing all songs, I could not find and result(s) inside the output directory.  Do I need to configure something on "zlibwapi.dll"?

**Comment by Exisi** [comment]
I encountered the same problem. I tried to put `C:\Program Files\Microsoft Office\root\Office16\ODBC Drivers\Salesforce\lib\zlibwapi.dll` to `SpleeterGUI\python\zlibwapi.dll`, it worked.

**Comment by boy1dr** [comment]
Antivirus often removes files from this project, the only way to get around it is to whitelist the application directory.

But if you are just looking for replacement files you can find them here https://github.com/boy1dr/SpleeterGUI_core/

in the case of zlibwapi.dll, just copy zlib.dll into the python folder and rename it.
https://github.com/boy1dr/SpleeterGUI_core/blob/main/python/h5py/zlib.dll
