### ISSUE TITLE
Why does the extracted accompaniment have a plosive?

### ISSUE THREAD

**Issue by qqvod** [boy1dr/SpleeterGui#26]
Why does the extracted accompaniment have a plosive?

When I use version 2.4 / 2.5 to extract the accompaniment, I find that the first 0.01s of the extracted accompaniment has a plosive sound, but v2.3 does not have this problem.

9013 original = original audio[9013-original.zip]
9013 accompany = accompaniment with plosives[9013-accompaniment.zip]

(https://github.com/boy1dr/SpleeterGui/files/4666592/9013-original.zip)
(https://github.com/boy1dr/SpleeterGui/files/4666593/9013-accompaniment.zip)

**Comment by boy1dr** [comment]
I upgraded spleeter to 1.5.1 in the V2.5 release so i'm guessing the previous spleeter version didn't react to your audio file the same way.
Does it still appear in the output files if you use WAV or FLAC as the source audio ?
I processed your original audio file in 2stem but did not get a pop like you did, very strange.

**Comment by qqvod** [comment]
My audio has MP3 / WAV / FLAC, and 21 of my 100 audios have pop.
The pop  sound may be easily overlooked, and the playback progress needs to be pulled forward a little before it can be heard.
I have tried different operating systems, the problem is the same, using version 2.3 does not have this problem.

**Comment by boy1dr** [comment]
I can confirm that spleeter version 1.5.1 does generate a DC Offset in the output files.
Version 1.4.3 does not (this was used in SpleeterGUI 2.3)

I have raised an issue on Deezer's spleeter github page if you want to follow along on this one
https://github.com/deezer/spleeter/issues/392

**Comment by boy1dr** [comment]
Bug has been confirmed by Deezer

**Comment by boy1dr** [comment]
Deezer have let me know they have addressed this in the latest version (2.0) of spleeter. it tested out fine, audio ouput is clean as a whistle :) 
In SpleeterGUI click Help -> Spleeter core upgrade
