### ISSUE TITLE
IDEA: You made Spleeter have a GUI, and automated the whole process of installing it so..

### ISSUE THREAD

**Issue by coolcraftnet18** [boy1dr/SpleeterGui#27]
Why don't you do the same for https://github.com/CorentinJ/Real-Time-Voice-Cloning 
That would be very convenient for many people including me, as I am unable to install Real Time Voice Cloning. I have also noticed that Spleeter and Real Time Voice Cloning use a lot of the same Python elements, so I think that it shouldn't be that hard for you?
Thanks,
David Devine

**Comment by boy1dr** [comment]
it's a good idea but i won't have time enough to look at anything like this for a while
