### ISSUE TITLE
Songs keep replacing other output files

### ISSUE THREAD

**Issue by JohnSmith2007** [boy1dr/SpleeterGui#29]
I'll use the 5stems model, and go to the folder that it gets outputted to, only to find that it generated tracks from the song that i previously generated. Not only that, but it went and replaced a bunch of my other songs with those files! What the fuck?! Also, generating tracks for multiple songs is broken, it just keeps generating tracks for the first file i select.
NOTE: I'm using the latest version, V2.5.

**Comment by boy1dr** [comment]
Hi John,
I have just tested V2.5. Dragged several mp3's in and split them in 5stem mode. moved those files then dragged more mp3's in and split them again in 5stem mode.
None of the first batch repeated or changed any files.
All mp3's where split as expected.
Sorry i cannot reproduce what happened to you :(
Are you able to give any more details on a test scenario?

**Comment by JohnSmith2007** [comment]
> Are you able to give any more details on a test scenario?

I can try. please hold.

**Comment by JohnSmith2007** [comment]
Ok, so i just tested it again and it didn't happen. Which is extremely confusing.
i recorded a vid for it.

https://drive.google.com/file/d/1zOI6rJ1XuqB0NZqWqxikkRctjE6-GMgU/view?usp=sharing

**Comment by boy1dr** [comment]
I can't replicate this behavior, feel free to open an issue again if you have a way for me to test this
