### ISSUE TITLE
bug:The output file does not change

### ISSUE THREAD

**Issue by maozelai** [boy1dr/SpleeterGui#31]
The output file does not change, only the original audio of the complex number will be output

**Comment by maozelai** [comment]
Will it be because the training model file fails to download and there is no correct training model to separate

**Comment by boy1dr** [comment]
yes, there was a problem with python downloading the pretrained model files so spleeter just copies the files as is. check your anti-virus/malware whatever hasn't blocked python.
more info here https://makenweb.com/spleeter_help.php
