### ISSUE TITLE
Installer link (OneDrive) is down

### ISSUE THREAD

**Issue by embql** [boy1dr/SpleeterGui#32]
Hi

Your link to the installer at https://makenweb.com/spleeter2.php is down (at the moment).
url = https://1drv.ms/u/s!AhbM98WiPUJYmTA106RumxHrovS7?e=HgF2ah 

cheers
Lasse

**Comment by boy1dr** [comment]
thanks for letting me know. onedrive as it turns out isn't the best for file hosting

**Comment by boy1dr** [comment]
fixed
it's hosted on my server now, hope it doesn't blow it up
https://makenweb.com/spleeter2.php
