### ISSUE TITLE
Feature request: add duration -d option

### ISSUE THREAD

**Issue by h-michinomiya** [boy1dr/SpleeterGui#37]
The spleeter is unable to output audio files longer than 10 minutes.
But I tried adding the d command and it works fine.

I want SpleeterGui to process audio files longer than 10 minutes automatically and correctly as well.

**Comment by boy1dr** [comment]
i'll add the -d option in for the next release, you will be able to specify the value.
However i did not write spleeter and cannot guarantee it will work in all scenario's some crashing can be expected.
The JSON config files (2stems, 4stems, 5stems) allow you to change some settings, you will find them here
C:\Users\YOURNAME\AppData\Roaming\SpleeterGUI
Perhaps there's a way to set duration in there in the meantime ;)

**Comment by boy1dr** [comment]
New version 2.7 was uploaded yesterday, it has the duration option.
MS Defender has once again detected it as a trojan, But MS gave it the all clear earlier today.
More info on that here https://github.com/boy1dr/SpleeterGui/issues/36
