### ISSUE TITLE
Request for accessibility improvements

### ISSUE THREAD

**Issue by GianlucaApollaro** [boy1dr/SpleeterGui#4]
Hi there,
First of all Thank you for this project that is fantastic so we don't have to run spleeter using a command line.
I'm a blind user and I have a little issue with how your latest version works.
In V1.0 there was a button to add a song and that could be easily accessed using my screen reader that is NVDA. In V2 though, that button seems to be gone and unfortunately the drag and drop feature is not available if using a screen reader because a blind user can not use the mouse.
Can you please add that button again? Keeping both features maybe? I don't care if I can't batch process.
Thanks a lot for the great work.

**Comment by boy1dr** [comment]
Apologies i didn't think of that!
I have released version 2.3 which has a button to select music files and begin processing.
I also updated the tab order and accessibility name & description of all on screen controls and added a system default sound on completion.
Hopefully this makes the app more usable, let me know how it goes :)

Github has been updated and here is a link to the latest MSI installer
https://1drv.ms/u/s!AhbM98WiPUJYmSsVUi8LeNVbf14a?e=LBOgP9
