### ISSUE TITLE
latest version of splleter Gui keeps closing automatically

### ISSUE THREAD

**Issue by dendrobium1** [boy1dr/SpleeterGui#42]
Hi.  I have been having an issue whenever I try to run "SpleeterGUI_V2.7".
Everytime I start the program, it runs for several seconds and just closes.  I have scanned my system for viruses with two different anti-viruses, and nothing comes up.  The first time I ran Spleeter, it worked fine, but than closed after it was done separating  the song.  anytime I have tried to run it after that it just closes after about 5 seconds.
I have also have tried completely uninstalling and re-installing as well, but this problem is still there.
I would like to note that SpleeterGui is the only program I am having this issue with.

**Comment by boy1dr** [comment]
@dendrobium1 This would probably be windows defender.
There is more detail here https://github.com/boy1dr/SpleeterGui/issues/36
My installed copy of SpleeterGUI_V2.7 also closes after about 5 seconds and it is defender that is doing it. If i tell defender to allow the program then it stays running.

This is a very annoying problem for me. I make exactly zero dollars from this project so i can't devote any resources to fight the constant false detection's from windows defender.

**Comment by dendrobium1** [comment]
Hi Chris. Thank you so much for the quick response. It's disappointing to know that Microsoft is still flagging this. However, I am somewhat relieved to know that I am not the only one having this problem. Also, a huge thank you for making this Gui four spleeter. It makes everything so much easier for those of us that don't know how to use command line￼

**Comment by Gusher** [comment]
Open Windows Defender Security Center.
    Click Virus & threat protection.
    Click the Virus & threat protection option.
    Under "Exclusions," click the Add or remove exclusions option.
    Click the Add an exclusion button.

Am using Norton and it's all fine on my end...

**Comment by boy1dr** [comment]
Version 2.8 is now available.
I have compiled this version as 64bit to avoid defender false positives.
