### ISSUE TITLE
Trouble downloading finetune model

### ISSUE THREAD

**Issue by dendrobium1** [boy1dr/SpleeterGui#43]
I already have the fine-tune models saved in C:\users: \sername\appdata\roaming\spleetergui.
I even labeled model name in the .json files to 2stems-finetune etc. I was able to do this perfectly fine with the previous versions, however this one keeps downloading the regular model can using that.

**Comment by boy1dr** [comment]
i moved the source json files in this version because you can set your own python path now.
the configs can be found here now C:\Program Files (x86)\Maken it so\SpleeterGUI\configs
