### ISSUE TITLE
Maximum song length ?

### ISSUE THREAD

**Issue by kevjee** [boy1dr/SpleeterGui#44]
Hi, I maybe was to fast reading updates but I don't see any information about this new feature.
Best regards !
Kevin Jee

**Comment by dendrobium1** [comment]
Hi Kevin. That feature is definitely in this latest update. Look for the box that says "600 seconds "you are able to type in the second manually. I tried this on a song that was around 14 minutes. It worked great., however. I tried a song that was nearly 25 minutes, and although it said that it completed successfully, the track was nowhere in my output folder.￼. ￼ hope this helped you.

**Comment by kevjee** [comment]
Thanks for the infos... I know it is there, but what is the purpose of this box exactly?
Nothing obvious comes out of my mind about it... 😁
________________________________
De : dendrobium1 <notifications@github.com>
Envoyé : vendredi 31 juillet 2020 18:55
À : boy1dr/SpleeterGui <SpleeterGui@noreply.github.com>
Cc : kevjee <kevin.jee@outlook.be>; Author <author@noreply.github.com>
Objet : Re: [boy1dr/SpleeterGui] Maximum song length ? (#44)


Hi Kevin. That feature is definitely in this latest update. Look for the box that says "600 seconds "you are able to type in the second manually. I tried this on a song that was around 14 minutes. It worked great., however. I tried a song that was nearly 25 minutes, and although it said that it completed successfully, the track was nowhere in my output folder.￼. ￼ hope this helped you.

**Comment by boy1dr** [comment]
@kevjee it places a limit on the amount of computer resources that spleeter is allowed to use.
By default the maximum song length is 5 minutes. 
But you might want to separate an hour long lecture to extract the voice out of background noise, you can bump up the duration value for the job then bring it back down for smaller jobs.

**Comment by kevjee** [comment]
ok I see.... Thank you !
________________________________
De : Chris Mitchell <notifications@github.com>
Envoyé : samedi 1 août 2020 04:23
À : boy1dr/SpleeterGui <SpleeterGui@noreply.github.com>
Cc : kevjee <kevin.jee@outlook.be>; Mention <mention@noreply.github.com>
Objet : Re: [boy1dr/SpleeterGui] Maximum song length ? (#44)


@kevjee<https://github.com/kevjee> it places a limit on the amount of computer resources that spleeter is allowed to use.
By default the maximum song length is 5 minutes.
But you might want to separate an hour long lecture to extract the voice out of background noise, you can bump up the duration value for the job then bring it back down for smaller jobs.

**Comment by holduan** [comment]
> @kevjee it places a limit on the amount of computer resources that spleeter is allowed to use.
> By default the maximum song length is 5 minutes.
> But you might want to separate an hour long lecture to extract the voice out of background noise, you can bump up the duration value for the job then bring it back down for smaller jobs.

I tried to raise the "duration" in "SpleeterGui.exe.config" to 1500 and "Maxium song lengt" to 1500, but it didn't work either, no output after Run complete. Is there a problem with my settings?
