### ISSUE TITLE
New 4 and 5 stem models crash while processing (python stops working)

### ISSUE THREAD

**Issue by silviokowald** [boy1dr/SpleeterGui#45]
2 stem model works fine, but the other two (4 and 5 stems) crash python while processing. was working fine before updating the spleeter core. 

i am using spleeter GUI 2.5 with spleeter 1.5.4. 

is this a problem with the GUI or is the problem at deezers new models? 

and if so is it possible to load previous versions of these models?

**Comment by boy1dr** [comment]
There's no problems that i'm aware of.
You can try deleting the models and running them again. this will force a new download of the models.
They are located here C:\Users\<YOURNAME>\AppData\Roaming\SpleeterGUI\pretrained_models
Just delete the folders 4stems & 5stems
The next time you run SpleeterGUI they will download automatically.

**Comment by silviokowald** [comment]
Thx alot for the reply! I will try that!

**Comment by silviokowald** [comment]
It worked! Thank you for the quick help! great GUI btw!

**Comment by boy1dr** [comment]
Very good 
Thanks for the kind words :)
