### ISSUE TITLE
"Click" noise at the beginning of output audio files

### ISSUE THREAD

**Issue by VincyZed** [boy1dr/SpleeterGui#46]
In [Dylan Tallchief's latest video](https://www.youtube.com/watch?v=JAg_Lzb6WVI), he mentions a clicking noise at the beginning of the splitted output files. I decided to give it a try, and I can confirm the same issue.

Thanks for this great program, I've tried Spleeter in the past but was unable to get it working in the command line. This is much easier and it works like a charm (apart from this small click noise I just mentioned) :)

**Comment by boy1dr** [comment]
Thanks for the kind words :)
This is covered in Frequent question #2 https://makenweb.com/spleeter_help.php

You can chose to wait for a fix or downgrade to the older version provided on the help page.

**Comment by VincyZed** [comment]
My pleasure!
Oh sorry, didn't see that. Thank you!
