### ISSUE TITLE
Corrupted Output on over 6min

### ISSUE THREAD

**Issue by Gusher** [boy1dr/SpleeterGui#49]
Tried to process a 15min long song on 2 channel model 
and the resulting output is corrupted about half way..

**Comment by boy1dr** [comment]
Try encoding your audio in a different format.
I know deezer put the 5 minute limit on there for a reason but you should be able to get more than that on a decent computer with lots of ram.
You might also try the command line method to rule out any changes in the json configuration files.

**Comment by Gusher** [comment]
...ok, will esperiment more with it.. thanks!
