### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by jdpnyc** [boy1dr/SpleeterGui#5]
Hi in version  1.1 everything works great.   when I updated to v2.3   when I  do a 5 stem output all the files are the same

**Comment by boy1dr** [comment]
sounds like the 5stem model didn't download correctly. (security/antivirus maybe?)
if the model doesn't download, you only get a copy of your source audio in the output folder.

The stem models are located in your appdata folder, mine is 
C:\Users\chris\AppData\Roaming\SpleeterGUI\pretrained_models\5stems

if that folder exists, delete it and try running the spleetergui again in 5stem mode.

The files it is trying to download to that folder are here
https://github.com/deezer/spleeter/releases/download/v1.4.0/5stems.tar.gz

**Comment by jdpnyc** [comment]
thank you that work, I am stemming one type  of music ,  What would best way of going about getting great results, Do I need to create my own music template for lack of better word from my music?.  Thank you Chris

**Comment by boy1dr** [comment]
Training the A.I. for the instruments used in tracks you want to separate would be the best approach. I haven't tried training but there's some info about it on spleeters github page
https://github.com/deezer/spleeter/wiki/2.-Getting-started#train-model
