### ISSUE TITLE
Translation to PT-BR

### ISSUE THREAD

**Issue by averaldofh** [boy1dr/SpleeterGui#57]
I'm very begginer at coding, and I actually only had experience with embbeded programming. But if you wish I can translate to PT-BR if it is an easy task to do.

**Comment by boy1dr** [comment]
Thanks for the offer, i have a new version coming out soon with translations provided by an online localization service. if the translation isn't accurate you will be able to update them there.

**Comment by averaldofh** [comment]
Nice! Also i'm sorry if I didn't use the 'issue' tab the right way.

**Comment by boy1dr** [comment]
All good buddy, just close the issue off when your done :)
