### ISSUE TITLE
Flute missed

### ISSUE THREAD

**Issue by Varu92** [boy1dr/SpleeterGui#58]
Flute is consistently missed or split into vocal and accompaniment, not sure if adding it in would be easy or not, but would be awesome if you could

**Comment by boy1dr** [comment]
It's not easy to add in sorry. It would need to be added to the training model and re-evaluated.
When Deezer made Spleeter they used a music stem file collection called MusDB which is about 22GB of audio, any instruments in there would have been learned by the AI.
