### ISSUE TITLE
Will it work on an old Notebook?

### ISSUE THREAD

**Issue by Paton77** [boy1dr/SpleeterGui#59]
Hi, will it work on my notebook that has the following specs?:
Intel (R) Core (TM) 2 Duo CPU T6670 @2.20 Ghz processor. 64 bits / Ram 6 Gb
Thanks in advance

**Comment by boy1dr** [comment]
According to intel this CPU doesn't have AVX support which spleeter need to run.
https://ark.intel.com/content/www/us/en/ark/products/42109/intel-core-2-duo-processor-t6670-2m-cache-2-20-ghz-800-mhz-fsb.html
