### ISSUE TITLE
Spleeter ne fonctionne pas

### ISSUE THREAD

**Issue by fodratou** [boy1dr/SpleeterGui#6]
Bonjour,
J'ai installé SpleeterGui sous Win10 avec un PC i7 dernière génération doté de 64 Go de mémoire. Au premier lancement la dll Vcruntime manquée. Je l'ai donc téléchargée et installé dans System32 seulement car elle était présente dans SysWOW64. Maintenant quand je tente une extraction, il n'y a pas de message d'erreur mais le dossier de destination est vide ! Au secours, merci et bonne journée.

**Comment by boy1dr** [comment]
https://github.com/deezer/spleeter/wiki/5.-FAQ

**Comment by fodratou** [comment]
Thank you Boy1dr but by looking further, I discovered that the Visual basic C ++ 2015 was at fault. I downloaded and installed it and now everything is working. Thank you and a bonjoiur from France.
