### ISSUE TITLE
Why does it need to install python in C:\? Furthermore, moving python.exe and selecting a new location does not work [Windows 7]

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [boy1dr/SpleeterGui#61]
The .msi installer apparently has an option to "change" the install directory, but that's just for a few tiny files. The installer still plonks a >1GB folder in my C:\ drive, located at AppData\Roaming. 

Moving the python folder and trying to select a new location for python.exe from "Advanced>Set python path" does not work, no matter what folder I select it's still "unable to find python.exe". 

Could this be fixed by adding the option to choose the python location from the installer itself?

---
Another and more specific problem I have is with my Windows Classic color scheme on Windows 7, which has white text on a dark background. [The buttons and text are not visible](https://i.imgur.com/bqoAhWx.png) - how can this be fixed? Can I modify the installer somehow?

**Comment by boy1dr** [comment]
ahhh dang, on both counts. i'll sort it out and upload a fix.
The installer only deals with the application, the SpleeterGUI folder is specifically placed in roaming so python has write access there.
The fix will be able to find it on any drive you choose tho. i'll update this repo so you can just grab the new exe.
rebuilding the installer sounds like a tomorrow job ;)

**Comment by boy1dr** [comment]
fix has been posted.
grab this https://github.com/boy1dr/SpleeterGui/blob/master/SpleeterGui/bin/Release/SpleeterGui.exe
and put it in C:\Program Files (x86)\Maken it so\SpleeterGUI
I also updated the language files to reflect the option "set python path" change to "set SpleeterGUI path".
When you use that menu option be sure to select the SpleeterGUI path not the python one ;)
Hopefully the color fix also works for you ;)

**Comment by iFUCKINGHATEcomputers** [comment]
[The text - it's beautiful.](https://i.imgur.com/1pF2gPL.png) And when I selected the new SpleeterGUI folder location the program works gloriously. Thank you.

However, for posterity's sake, [it might need a few tiny tweaks](https://i.imgur.com/CTI3S9P.png) - then it will be perfect.

**Comment by boy1dr** [comment]
fixed :)

get https://github.com/boy1dr/SpleeterGui/blob/master/SpleeterGui/bin/Release/SpleeterGui.exe
put it here  C:\Program Files (x86)\Maken it so\SpleeterGUI

get https://github.com/boy1dr/SpleeterGui/blob/master/SpleeterGui/languages_source/english.xml
put it here  C:\Program Files (x86)\Maken it so\SpleeterGUI\languages

i'll rebuild the installer in a few hours once i've checked it all out (lengthy process).

i also added a tensorflow fix in this one that gets rid of the pop at the beginning and end of the output stems as suggested by the Deezer team.

**Comment by iFUCKINGHATEcomputers** [comment]
Brilliant!
