### ISSUE TITLE
ImportError: Không thể tìm thấy DLL ( s) 'msvcp140.dll hoặc msvcp140_1.dll'.

### ISSUE THREAD

**Issue by tansro** [boy1dr/SpleeterGui#65]
chào admin, cho mình hỏi đây là lỗi gì, cách khắc phục thế nào admin. Cảm ơn bạn.

Tệp "C: \ Users \ PC NMT \ AppData \ Roaming \ SpleeterGUI \ python \ Lib \ site-pack \ tensorflow \ python \ pywrap_tensorflow.py", dòng 28, trong
self_check.preload_check ()
Tệp "C: \ Users \ PC NMT \ AppData \ Roaming \ SpleeterGUI \ python \ Lib \ site-pack \ tensorflow \ python \ platform \ self_check.py ", dòng 61, trong preload_check
%" hoặc ".join (thiếu))
ImportError: Không thể tìm thấy DLL ( s) 'msvcp140.dll hoặc msvcp140_1.dll'. TensorFlow yêu cầu các tệp DLL này được cài đặt trong thư mục có tên trong biến môi trường% PATH% của bạn. Bạn có thể cài đặt các DLL này bằng cách tải xuống "Microsoft C ++ Redistributable cho Visual Studio 2015, 2017 và 2019" cho nền tảng của bạn từ URL này: https://support.microsoft.

Chạy hoàn tất
![1](https://user-images.githubusercontent.com/65890487/96024720-52a2c800-0e7e-11eb-944d-c40e3032fae3.png)

**Comment by spicefan25** [comment]
Chào anh, 
Tôi có cùng mối quan tâm như bạn, tôi sẽ phải gỡ cài đặt hoàn toàn phần mềm với ví dụ "Revo Uninstaller" và cài đặt lại phiên bản 2.8 mà không cập nhật "spleeter core upgrade"
I have the same concerns as you, it will be necessary to completely uninstall the software with for example "Revo Uninstaller"
<img width="402" alt="2020-10-25 01_48_58-SpleeterGUI 2 8" src="https://user-images.githubusercontent.com/73409549/97095800-4f6cc080-1664-11eb-8570-18d8088e9bc3.png">
 and reinstall version 2.8 without "spleeter core upgrade"

**Comment by boy1dr** [comment]
There is a component missing from your windows. please install it from here https://aka.ms/vs/16/release/vc_redist.x64.exe
