### ISSUE TITLE
SpleeterGUI hard crashes Windows/reboots my PC

### ISSUE THREAD

**Issue by ManOrMonster** [boy1dr/SpleeterGui#66]
I installed Spleeter GUI then ran the Spleeter core upgrade. After that I tried to separate a track into 2 parts, and my computer just restarted. Tried it again, same result.

SpleeterGUI 2.8
Spleeter Version: 2.0.1
Windows 10 1903,  build 18362.1082
Intel Core i7-4790K
32GB RAM

**Comment by boy1dr** [comment]
your computer should have no problems running spleeter, a hard crash is really unusual.
maybe uninstall it and download the MSI again.
