### ISSUE TITLE
issue with converting, this is from the box 

### ISSUE THREAD

**Issue by leonroberts1972** [boy1dr/SpleeterGui#74]
Starting processing of all songs
Processing C:\Users\leonr\Desktop\ACID - HARD\03. Acid Rain (Original Mix) .mp3
ERROR:spleeter:FFMPEG error: b"ffmpeg version git-2019-11-01-53c21c2 Copyright (c) 2000-2019 the FFmpeg developers\r\n  built with gcc 9.2.1 (GCC) 20191010\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf\r\n  libavutil      56. 35.101 / 56. 35.101\r\n  libavcodec     58. 60.100 / 58. 60.100\r\n  libavformat    58. 33.100 / 58. 33.100\r\n  libavdevice    58.  9.100 / 58.  9.100\r\n  libavfilter     7. 66.100 /  7. 66.100\r\n  libswscale      5.  6.100 /  5.  6.100\r\n  libswresample   3.  6.100 /  3.  6.100\r\n  libpostproc    55.  6.100 / 55.  6.100\r\nGuessed Channel Layout for Input Stream #0.0 : stereo\r\nInput #0, f32le, from 'pipe:':\r\n  Duration: N/A, bitrate: 2822 kb/s\r\n    Stream #0:0: Audio: pcm_f32le, 44100 Hz, stereo, flt, 2822 kb/s\r\nC:\\Users\\leonr\\Desktop\\03. Acid Rain (Original Mix) /other.wav: No such file or directory\r\n"
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
did it put anything in the output folder?
looks like there is a problem with the file path "No such file or directory"

**Comment by leonroberts1972** [comment]
No there was nothing in the file, that is my issue

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by boy1dr** [comment]
there might be a problem with the file path of either the source song or output folder. try changing their locations and give it another try.
Do you have anti virus or anti-malware protection that might be stopping python from working with your files ?

**Comment by leonroberts1972** [comment]
No still the same, I have allowed the software to get through my anti virus

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by boy1dr** [comment]
i'm sorry i don't know what else to tell you. the error message states "No such file or directory", that is the problem.

Either the source song has a path not supported by python (spaces and special characters can do this).
Or the output path cannot be written to by python.

**Comment by leonroberts1972** [comment]
I have looked around at the software, it says it can't find python. Exe, but I know it on there, this is a bit fucked up

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by boy1dr** [comment]
no need for language

python will be located here on your computer
C:\Users\leonr\AppData\Roaming\SpleeterGUI\python\python.exe

best of luck

**Comment by leonroberts1972** [comment]
Thank you, will have a look when I'm home

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by leonroberts1972** [comment]
Hi, there is no python exe  there

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
