### ISSUE TITLE
Ecriture en sorti

### ISSUE THREAD

**Issue by Fredy974** [boy1dr/SpleeterGui#77]
Bonjour, depuis aujourd'hui
 la séparation  des stems se passe bien puisque je n'ai pas de message d'erreur, mais dans mon dossier de sortie je n'ai rien alors qu'il me dit qu'il m'indique que cela c'est bien passé.
Avez-vous eu ce problème?
Ci joint une capture d'écran
Cordialement
![2020-12-17](https://user-images.githubusercontent.com/58072485/102448363-4380f780-4032-11eb-86b9-266ae983cceb.png)

**Comment by boy1dr** [comment]
hello, i hope translate works ok here.
It looks like a DLL error.
This may not fix.
please see first item on help page

bonjour, j'espère que traduire fonctionne bien ici.
Cela ressemble à une erreur DLL.
Cela peut ne pas résoudre.
s'il vous plaît voir le premier élément sur la page d'aide

https://makenweb.com/spleeter_help.php

**Comment by Fredy974** [comment]
Merci d'avoir répondu la tarduction de mon côté est bonne effectivement
c'est un problème de DLL, a savoir j'ai un prcesseur intel Xéon

Le jeu. 17 déc. 2020 à 06:52, Chris Mitchell <notifications@github.com> a
écrit :
