### ISSUE TITLE
DOWNLOAD BROKEN

### ISSUE THREAD

**Issue by Gusher** [boy1dr/SpleeterGui#78]
The google drive download link for SpleeterGUI seems broken...

**Comment by boy1dr** [comment]
seems to be working fine nor me. temporary issue?

**Comment by jamasi** [comment]
Just to add some explanation to this: Google is limiting the number of downloads for large files (I suppose in attempt to stop virtual piracy. After a while the download will work again (and I suppose it will always work for the owner of the drive account, so you don't notice any problem here).

It might be an Idea to have the installer stored at archive.org or some other site that does a better job at hosting than google drive.

**Comment by boy1dr** [comment]
@jamasi Thanks for the extra info :)
I have searched for a host that can service the 4.5TB (on average) monthly bandwidth requirements but they all want an arm and a leg for it.
There is an alternate download link there now that works but throttles when too many people are downloading simultaneously.

**Comment by jamasi** [comment]
Another alternative would be to offer a bittorrent download that is seeded with a (rate limited) webseed.

**Comment by Gusher** [comment]
Looks like firefox browser has issue downloading it, but the other browsers are ok... MediaFire for sharing files is far the best I've seen...

**Comment by boy1dr** [comment]
@Gusher Thanks, that one looks pretty good

**Comment by boy1dr** [comment]
Sigh, MediaFire won't do at all. i'm 5 days in with currently 1600 downloads of a 905mb file (1.448TB). there's only 256GB remaining bandwidth.
It will cost $50AUD for 1000GB bandwidth (just over 3 days of downloads).
The search for a file host continues...

**Comment by boy1dr** [comment]
i'll get it sorted
