### ISSUE TITLE
I want to contribute on korean language

### ISSUE THREAD

**Issue by yeonggille** [boy1dr/SpleeterGui#81]
Hello, I'm the one who told you to join the team at the youtube, But unfortunatly, I think you accidently deleted the email i sent you with korean.xml. So i create the Github account and request you that, could i have a write permission to upload the Korean language file? Thanks, and have a nice day

**Comment by yeonggille** [comment]
[Spleeter_gui_korean_MK1.zip](https://github.com/boy1dr/SpleeterGui/files/5790419/Spleeter_gui_korean_MK1.zip)
Just in case, XML is inside the ZIP

**Comment by boy1dr** [comment]
Hi
there is no "write permission" in github, normally you would do a pull request.
But i have added your original file now, if there are no changes to it i will do a commit tomorrow.

**Comment by yeonggille** [comment]
Thanks for reply! You can now use the korean.xml file on the MK2, which i just upload now, not the MK1 i edited out. I hope you have a good luck for whole this year! Have a good day!

**Comment by yeonggille** [comment]
Hello, and again, I visited thread just in case to check if you had a glitch with language file. have you successfully committed the file without having an error?

**Comment by boy1dr** [comment]
Apologies for the delay, i have had some unfortunate family business to attend to.
i have a few updates to make today hopefully i can commit the changes today :)

**Comment by boy1dr** [comment]
The latest github commit has the changes in it. i will repackage the installer and update that today as well.
Thanks
