### ISSUE TITLE
Spleeter 2.1.2 Problem

### ISSUE THREAD

**Issue by adasahin** [boy1dr/SpleeterGui#82]
Hi, I'm not sure what's going on but this could be makes sense. I have updated the core SpeeterGUI.

Starting processing of all songs
Processing E:\mp3\hello world.mp3
Usage: __main__.py separate [OPTIONS] FILES...
Try '__main__.py separate --help' for help.
Error: Missing argument 'FILES...'.
Finished processing all songs

Run complete

(Also i'm using SpleeterGUI 2.8 right now. I couldn't set the python on the Spleeter 2.9 version.)
What can i do?

**Comment by boy1dr** [comment]
My project has an installer that uses a special version of python (python embedded). There is no need to install python separately. it should just be a download/install & run type situation.
Deezer has recently release Spleeter 2.1 which has some breaking changes in it (i just learned this morning).
So it would be best if you don't run a Spleeter update after install my gui.
i'll work on a fix in the coming days

**Comment by adasahin** [comment]
Thanks a lot!

**Comment by gorkalombar** [comment]
Same problem here! I hope it gets solved soon!

**Comment by gggccc44** [comment]
Same problem here!
2.8 ok，2.8 Spleeter 2.1.2 ok。
win7 64

**Comment by lilei105** [comment]
The latest version of Spleeter removed the -i arg. So all you have to do is load boy1dr's source code, find line #231, something like
`ProcessStartInfo processStartInfo = new ProcessStartInfo(pyPath, @" -W ignore -m spleeter separate " + (char)34 + filename + (char)34 + " -o " + (char)34 + txt_output_directory.Text + (char)34 + " -d "+ (duration.Value).ToString()  + " -p " + (char)34 + storage + @"\config.json" + (char)34);    //-B tensorflow`
and remove the -i, then everything would be fine.

**Comment by markanini** [comment]
Anyone able to share a build for Windows with the fix?

**Comment by adasahin** [comment]
> The latest version of Spleeter removed the -i arg. So all you have to do is load boy1dr's source code, find line #231 in Form1.cs, something like
> `ProcessStartInfo processStartInfo = new ProcessStartInfo(pyPath, @" -W ignore -m spleeter separate -i " + (char)34 + filename + (char)34 + " -o " + (char)34 + txt_output_directory.Text + (char)34 + " -d "+ (duration.Value).ToString() + " -p " + (char)34 + storage + @"\config.json" + (char)34); //-B tensorflow`
> and remove the -i, then everything would be fine.

I have removed the "-i" section but it did not work
Maybe i should do something more?
(By the way, thanks!)

**Comment by boy1dr** [comment]
Hi everyone, i have patched the code and updated github. 
The patched exe can be downloaded here https://makenweb.com/downloads/SpleeterGui.exe
Just replace the exe found here...
C:\Program Files (x86)\Maken it so\SpleeterGUI\SpleeterGui.exe

**Comment by markanini** [comment]
Having no luck with the exe above, getting the following output:
`Starting processing of all songs
Processing C:\music\song.flac
usage: spleeter separate [-h] [-a AUDIO_ADAPTER] [-p CONFIGURATION]
                         [--verbose] -i INPUTS [INPUTS ...] [-o OUTPUT_PATH]
                         [-f FILENAME_FORMAT] [-d DURATION] [-s OFFSET]
                         [-c {wav,mp3,ogg,m4a,wma,flac}] [-b BITRATE] [-m]
                         [-B {tensorflow,librosa,auto}]
spleeter separate: error: the following arguments are required: -i/--inputs
Finished processing all songs

Run complete
`
Not sure whats wrong

**Comment by boy1dr** [comment]
You have to have updated spleeter for the new command to work. 
(this exe file is a patch for broken SpleeterGUI installs that had been updated).
You can run the manual update or install the latest version from https://makenweb.com/SpleeterGUI

To manually update Spleeter, open a command prompt (press windows key, type "cmd" and hit enter)
Run the following command, replace YOURNAME with your windows account name

C:\Users\YOURNAME\AppData\Roaming\SpleeterGUI\python\python.exe -m pip install --upgrade spleeter

**Comment by markanini** [comment]
Thx for clarifying, It's working for me now.
