### ISSUE TITLE
ImportError: cannot import name 'DtypeObj' from 'pandas._typing'

### ISSUE THREAD

**Issue by trigger460** [boy1dr/SpleeterGui#83]
I had installed this in version 2.6 before and it functioned well.But l unstalled and updated it to 2.8 a few days ago,then it went wrong.No matter which version I use,this problem will arise.
Could anyone handle it for me?Thanks!

**Comment by boy1dr** [comment]
The main change with V2.8 was 64bit. if you are using a 32bit OS you will have trouble running V2.8 & V2.9
Currently there is a problem with the latest version Spleeter in SpleeterGUI.
So once you install, do not upgrade the spleeter core until it's fixed.
