### ISSUE TITLE
Seperating to more than two parts results in no output.

### ISSUE THREAD

**Issue by markanini** [boy1dr/SpleeterGui#85]
Vocal + accompaniment works fine but selecting 3-5 parts results in no output.

**Comment by boy1dr** [comment]
you can try and download the stem models again
Go to this folder, replace chris with your windows account name
C:\Users\chris\AppData\Roaming\SpleeterGUI\pretrained_models

and delete the folders 4stems & 5stems.
next time you run SpleeterGUI in 4&5 stem mode, they will be downloaded again.

**Comment by markanini** [comment]
Thanks that solved it.
