### ISSUE TITLE
Have you finished commit korean.xml onto 2.9?

### ISSUE THREAD

**Issue by yeonggille** [boy1dr/SpleeterGui#86]
Hello, this is yeonggill Lee who translated spleeter gui here. I was downloaded 2.9 Full installer and installed spleeter-gui, which is lastest uploaded on your makern it so hompage with clean install, I cannot find korean on the language section. If you could, could you check this one out when you have a time? Thanks!

**Comment by boy1dr** [comment]
ahh yes i missed adding the latest language files. recompiling the installer now, will let you know when it's uploaded.

**Comment by boy1dr** [comment]
website has been updated with new installer with the additional language files
https://makenweb.com/SpleeterGUI
