### ISSUE TITLE
file name buglet

### ISSUE THREAD

**Issue by fixer-dave** [boy1dr/SpleeterGui#89]
just thought I would let you know of a small bug... DONT have a space in front of the dot eg: 'name .wav' or 'name .mp3' ...these fail .If your file name has a space then the dot, it wont work. seems ok with () and - in the title, hope that makes sense, haven't tried other symbols yet like # = + [] these might be ok but remove them if spleeter fails. dave using in win 10, otherwise ok

**Comment by boy1dr** [comment]
Thanks for letting me know, i'll have a look at it after work.
it might be a limitation of ffmpeg/spleeter though, as a command line interface, file names need to be perfect.

**Comment by fixer-dave** [comment]
yes, I have the command line version and I had to remove everything, spaces and all symbols, this win version is very good and only took a bit of logic to isolate bug. cheers  dave
