### ISSUE TITLE
Binaries on Github?

### ISSUE THREAD

**Issue by junh1024** [boy1dr/SpleeterGui#9]
You know you can put binaries on Github using the releases page, instead of 1D, GD, etc, right?

**Comment by boy1dr** [comment]
no i haven't read much about it. i guess i just make stuff and put it out there for others to use, normally that suffices but this one had a few revisions.
What do you mean by 1D, GD etc ?

**Comment by junh1024** [comment]
onedrive, google drive, et cetera.
