### ISSUE TITLE
Sorry, you can't view or download this file at this time.

### ISSUE THREAD

**Issue by kajlando** [boy1dr/SpleeterGui#90]
"Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator." - Google Drive

Would it be possible to add a second download site like Nextcloud or MEGA?

**Comment by boy1dr** [comment]
That's unfortunate. i was self-hosting the file but had complaints about download speed so i moved it to google cloud.
I have tried to find a host for the file but the bandwidth requirements are too large and hosting fee's too much.
I'm uploading it back to my site and will add a secondary link to the download page when ready

**Comment by boy1dr** [comment]
I have updated my site with the alternate download link
https://makenweb.com/SpleeterGUI
