### ISSUE TITLE
SpleeterGUI 2.8 Binary

### ISSUE THREAD

**Issue by Gusher** [boy1dr/SpleeterGui#99]
Anybody have a copy of v2.8 binary they can share? 2.9 is not working on my end...

**Comment by boy1dr** [comment]
whats going on with it ?

**Comment by Gusher** [comment]
I made a post about it.... it cannot find python.exe  ..even set it and still doesn't

**Comment by boy1dr** [comment]
The location of the python.exe is stored in the windows registry, running a different gui version won't change that.
So the python.exe you are pointing gui at should be something like 
C:\Users\YOUR_NAME\AppData\Roaming\SpleeterGUI\python\python.exe

There's a bunch of stuff in the parent fold that the gui needs. can you check that is all there?
![files](https://user-images.githubusercontent.com/5217188/112232434-4704ca00-8c84-11eb-93f4-3ae210faeb3a.png)

**Comment by boy1dr** [comment]
oh i just tested it, you need to select the SpleeterGUI folder, not the python folder. i should rename that menu item sorry.
![gui](https://user-images.githubusercontent.com/5217188/112232679-b37fc900-8c84-11eb-9dba-6b0ac7345255.png)

**Comment by Gusher** [comment]
I did that and still get that error.....will try one last install and try again..

**Comment by Gusher** [comment]
O, that workee, all good now... thanks for responding..... I think the app should automatically set that...

**Comment by boy1dr** [comment]
Glad to hear :)
It should be set with the default location on install. i don't know why it did that to you :/
